export type TextOverlay = { id: string; text: string; x: number; y: number; fontSize: number; color: string; fontWeight: "normal" | "bold" };
export type TransitionType = "none" | "fade" | "slide" | "zoom" | "crossfade";
export type EffectType = "none" | "bright" | "vintage" | "cool" | "warm" | "grayscale" | "contrast" | "soft";

export type ThemeTemplate = {
  id: string;
  name: string;
  emoji: string;
  description: string;
  backgroundColor: string;
  texts: Omit<TextOverlay, "id">[];
  transition: TransitionType;
  effect: EffectType;
  transitionDuration: number;
  secondsPerSlide: number;
  playbackSpeed: number;
};

export const THEMES: ThemeTemplate[] = [
  { id: "motivation", name: "Motivation", emoji: "🔥", description: "Punchy hook", backgroundColor: "#0f0f0f", transition: "zoom", effect: "contrast", transitionDuration: 1.0, secondsPerSlide: 2.5, playbackSpeed: 1.1, texts: [{ text: "STOP SCROLLING", x: 50, y: 28, fontSize: 40, color: "#ffffff", fontWeight: "bold" }, { text: "This changes everything", x: 50, y: 48, fontSize: 24, color: "#fbbf24", fontWeight: "bold" }, { text: "Save this for later", x: 50, y: 78, fontSize: 18, color: "#a3a3a3", fontWeight: "normal" }] },
  { id: "fitness", name: "Fitness", emoji: "💪", description: "Gym grind", backgroundColor: "#111827", transition: "slide", effect: "bright", transitionDuration: 0.7, secondsPerSlide: 2.0, playbackSpeed: 1.2, texts: [{ text: "DAY 47", x: 50, y: 22, fontSize: 52, color: "#22c55e", fontWeight: "bold" }, { text: "No excuses.", x: 50, y: 44, fontSize: 32, color: "#ffffff", fontWeight: "bold" }, { text: "Just results.", x: 50, y: 62, fontSize: 26, color: "#86efac", fontWeight: "normal" }] },
  { id: "business", name: "Business", emoji: "💼", description: "Clean editorial", backgroundColor: "#0c0a09", transition: "fade", effect: "contrast", transitionDuration: 1.1, secondsPerSlide: 3.0, playbackSpeed: 1.0, texts: [{ text: "THE TRUTH ABOUT", x: 50, y: 30, fontSize: 20, color: "#a8a29e", fontWeight: "normal" }, { text: "Building Wealth", x: 50, y: 48, fontSize: 34, color: "#fafaf9", fontWeight: "bold" }, { text: "in 2026", x: 50, y: 66, fontSize: 24, color: "#f59e0b", fontWeight: "bold" }] },
  { id: "travel", name: "Travel", emoji: "✈️", description: "Cinematic cool", backgroundColor: "#0c4a6e", transition: "crossfade", effect: "cool", transitionDuration: 1.6, secondsPerSlide: 3.5, playbackSpeed: 0.8, texts: [{ text: "Hidden gem", x: 50, y: 24, fontSize: 24, color: "#7dd3fc", fontWeight: "normal" }, { text: "You need to visit", x: 50, y: 46, fontSize: 32, color: "#ffffff", fontWeight: "bold" }, { text: "this place", x: 50, y: 66, fontSize: 28, color: "#e0f2fe", fontWeight: "bold" }] },
  { id: "food", name: "Food", emoji: "🍕", description: "Warm recipe", backgroundColor: "#7c2d12", transition: "zoom", effect: "warm", transitionDuration: 1.0, secondsPerSlide: 2.5, playbackSpeed: 1.0, texts: [{ text: "Recipe in 30 seconds", x: 50, y: 26, fontSize: 20, color: "#fdba74", fontWeight: "normal" }, { text: "You will CRY", x: 50, y: 48, fontSize: 38, color: "#ffffff", fontWeight: "bold" }, { text: "when you try this", x: 50, y: 70, fontSize: 22, color: "#fed7aa", fontWeight: "normal" }] },
  { id: "fashion", name: "Fashion", emoji: "👗", description: "Soft OOTD", backgroundColor: "#1e1b4b", transition: "zoom", effect: "soft", transitionDuration: 1.4, secondsPerSlide: 3.0, playbackSpeed: 0.85, texts: [{ text: "OUTFIT OF THE DAY", x: 50, y: 24, fontSize: 18, color: "#c4b5fd", fontWeight: "normal" }, { text: "Steal this look", x: 50, y: 46, fontSize: 32, color: "#ffffff", fontWeight: "bold" }, { text: "Link in bio", x: 50, y: 74, fontSize: 18, color: "#a78bfa", fontWeight: "normal" }] },
  { id: "neon", name: "Neon", emoji: "💜", description: "Cyber night", backgroundColor: "#0f0518", transition: "slide", effect: "cool", transitionDuration: 0.8, secondsPerSlide: 2.2, playbackSpeed: 1.15, texts: [{ text: "NIGHT MODE", x: 50, y: 30, fontSize: 28, color: "#e879f9", fontWeight: "bold" }, { text: "ON", x: 50, y: 52, fontSize: 64, color: "#22d3ee", fontWeight: "bold" }, { text: "Stay until the end", x: 50, y: 76, fontSize: 18, color: "#c026d3", fontWeight: "normal" }] },
  { id: "minimal", name: "Minimal", emoji: "✨", description: "Slow clean", backgroundColor: "#fafafa", transition: "fade", effect: "soft", transitionDuration: 1.5, secondsPerSlide: 3.5, playbackSpeed: 0.75, texts: [{ text: "less is more", x: 50, y: 44, fontSize: 32, color: "#171717", fontWeight: "normal" }, { text: "keep it simple", x: 50, y: 66, fontSize: 18, color: "#525252", fontWeight: "normal" }] },
  { id: "pov", name: "POV", emoji: "👀", description: "CapCut hook", backgroundColor: "#09090b", transition: "zoom", effect: "contrast", transitionDuration: 1.2, secondsPerSlide: 2.8, playbackSpeed: 1.0, texts: [{ text: "POV", x: 50, y: 22, fontSize: 56, color: "#f43f5e", fontWeight: "bold" }, { text: "you just found this", x: 50, y: 46, fontSize: 24, color: "#ffffff", fontWeight: "bold" }, { text: "wait for it...", x: 50, y: 76, fontSize: 18, color: "#a1a1aa", fontWeight: "normal" }] },
  { id: "grwm", name: "GRWM", emoji: "💄", description: "Soft glam", backgroundColor: "#4c0519", transition: "crossfade", effect: "warm", transitionDuration: 1.5, secondsPerSlide: 3.0, playbackSpeed: 0.85, texts: [{ text: "GRWM", x: 50, y: 24, fontSize: 44, color: "#fda4af", fontWeight: "bold" }, { text: "date night edition", x: 50, y: 46, fontSize: 22, color: "#ffffff", fontWeight: "bold" }, { text: "products in comments", x: 50, y: 76, fontSize: 16, color: "#fecdd3", fontWeight: "normal" }] },
  { id: "storytime", name: "Storytime", emoji: "📖", description: "Vintage story", backgroundColor: "#1c1917", transition: "slide", effect: "vintage", transitionDuration: 0.9, secondsPerSlide: 3.2, playbackSpeed: 0.9, texts: [{ text: "STORYTIME", x: 50, y: 24, fontSize: 32, color: "#fbbf24", fontWeight: "bold" }, { text: "you won't believe this", x: 50, y: 48, fontSize: 24, color: "#ffffff", fontWeight: "bold" }, { text: "part 1", x: 50, y: 76, fontSize: 18, color: "#a8a29e", fontWeight: "normal" }] },
  { id: "beforeafter", name: "Before/After", emoji: "⚡", description: "Hard cut reveal", backgroundColor: "#18181b", transition: "none", effect: "contrast", transitionDuration: 0.5, secondsPerSlide: 2.0, playbackSpeed: 1.0, texts: [{ text: "BEFORE", x: 28, y: 22, fontSize: 22, color: "#a1a1aa", fontWeight: "bold" }, { text: "AFTER", x: 72, y: 22, fontSize: 22, color: "#22c55e", fontWeight: "bold" }, { text: "same place. different life.", x: 50, y: 78, fontSize: 16, color: "#ffffff", fontWeight: "normal" }] },
  { id: "threetips", name: "3 Tips", emoji: "3", description: "Listicle pack", backgroundColor: "#172554", transition: "slide", effect: "cool", transitionDuration: 0.8, secondsPerSlide: 2.4, playbackSpeed: 1.05, texts: [{ text: "3 THINGS", x: 50, y: 26, fontSize: 32, color: "#93c5fd", fontWeight: "bold" }, { text: "nobody tells you", x: 50, y: 46, fontSize: 24, color: "#ffffff", fontWeight: "bold" }, { text: "save this", x: 50, y: 76, fontSize: 18, color: "#bfdbfe", fontWeight: "normal" }] },
  { id: "quote", name: "Quote", emoji: "💬", description: "B&W quote card", backgroundColor: "#0f172a", transition: "fade", effect: "grayscale", transitionDuration: 1.4, secondsPerSlide: 4.0, playbackSpeed: 0.7, texts: [{ text: "Make it look easy.", x: 50, y: 48, fontSize: 28, color: "#f8fafc", fontWeight: "bold" }, { text: "your next caption", x: 50, y: 72, fontSize: 16, color: "#94a3b8", fontWeight: "normal" }] },
  { id: "sale", name: "Sale", emoji: "🏷️", description: "Promo punch", backgroundColor: "#450a0a", transition: "zoom", effect: "bright", transitionDuration: 0.6, secondsPerSlide: 2.0, playbackSpeed: 1.2, texts: [{ text: "50% OFF", x: 50, y: 28, fontSize: 48, color: "#fde68a", fontWeight: "bold" }, { text: "this weekend only", x: 50, y: 50, fontSize: 22, color: "#ffffff", fontWeight: "bold" }, { text: "shop the link", x: 50, y: 76, fontSize: 18, color: "#fecaca", fontWeight: "normal" }] },
  { id: "realestate", name: "Listing", emoji: "🏠", description: "Luxury listing tour", backgroundColor: "#0b1220", transition: "crossfade", effect: "warm", transitionDuration: 1.6, secondsPerSlide: 3.5, playbackSpeed: 0.8, texts: [{ text: "JUST LISTED", x: 50, y: 22, fontSize: 20, color: "#fbbf24", fontWeight: "bold" }, { text: "Waterfront living", x: 50, y: 46, fontSize: 30, color: "#ffffff", fontWeight: "bold" }, { text: "DM for a private tour", x: 50, y: 76, fontSize: 16, color: "#cbd5e1", fontWeight: "normal" }] },
  { id: "luxury", name: "Luxury", emoji: "🥂", description: "Dark gold film", backgroundColor: "#111111", transition: "fade", effect: "contrast", transitionDuration: 1.8, secondsPerSlide: 3.8, playbackSpeed: 0.7, texts: [{ text: "QUIET LUXURY", x: 50, y: 28, fontSize: 24, color: "#d4af37", fontWeight: "bold" }, { text: "details matter", x: 50, y: 50, fontSize: 32, color: "#f5f5f4", fontWeight: "bold" }, { text: "follow for more", x: 50, y: 76, fontSize: 16, color: "#a8a29e", fontWeight: "normal" }] },
  { id: "wellness", name: "Wellness", emoji: "🧘", description: "Slow morning", backgroundColor: "#14532d", transition: "crossfade", effect: "soft", transitionDuration: 2.0, secondsPerSlide: 4.0, playbackSpeed: 0.7, texts: [{ text: "slow morning", x: 50, y: 28, fontSize: 24, color: "#bbf7d0", fontWeight: "normal" }, { text: "protect your peace", x: 50, y: 50, fontSize: 26, color: "#ffffff", fontWeight: "bold" }, { text: "breathe", x: 50, y: 76, fontSize: 18, color: "#86efac", fontWeight: "normal" }] },
  { id: "pets", name: "Pets", emoji: "🐾", description: "Cute warm", backgroundColor: "#422006", transition: "zoom", effect: "warm", transitionDuration: 0.9, secondsPerSlide: 2.4, playbackSpeed: 1.05, texts: [{ text: "meet the star", x: 50, y: 24, fontSize: 20, color: "#fdba74", fontWeight: "normal" }, { text: "good boy energy", x: 50, y: 48, fontSize: 28, color: "#ffffff", fontWeight: "bold" }, { text: "like if you smiled", x: 50, y: 76, fontSize: 16, color: "#fed7aa", fontWeight: "normal" }] },
  { id: "tutorial", name: "Tutorial", emoji: "🎬", description: "How-to steps", backgroundColor: "#1e1b4b", transition: "slide", effect: "bright", transitionDuration: 0.7, secondsPerSlide: 2.2, playbackSpeed: 1.1, texts: [{ text: "HOW TO", x: 50, y: 24, fontSize: 32, color: "#c4b5fd", fontWeight: "bold" }, { text: "do this in 10 seconds", x: 50, y: 48, fontSize: 22, color: "#ffffff", fontWeight: "bold" }, { text: "step 1", x: 50, y: 76, fontSize: 18, color: "#a78bfa", fontWeight: "normal" }] },
  { id: "countdown", name: "Countdown", emoji: "⏳", description: "Urgency pack", backgroundColor: "#3b0764", transition: "zoom", effect: "contrast", transitionDuration: 0.6, secondsPerSlide: 1.8, playbackSpeed: 1.25, texts: [{ text: "3... 2... 1...", x: 50, y: 28, fontSize: 28, color: "#e9d5ff", fontWeight: "bold" }, { text: "don't skip this", x: 50, y: 50, fontSize: 26, color: "#ffffff", fontWeight: "bold" }, { text: "ending is worth it", x: 50, y: 76, fontSize: 16, color: "#d8b4fe", fontWeight: "normal" }] },
  { id: "aesthetic", name: "Aesthetic", emoji: "🌸", description: "Soft-life vintage", backgroundColor: "#4a1942", transition: "crossfade", effect: "vintage", transitionDuration: 1.7, secondsPerSlide: 3.4, playbackSpeed: 0.75, texts: [{ text: "main character", x: 50, y: 28, fontSize: 22, color: "#fbcfe8", fontWeight: "normal" }, { text: "soft life loading", x: 50, y: 50, fontSize: 26, color: "#ffffff", fontWeight: "bold" }, { text: "sound on", x: 50, y: 76, fontSize: 16, color: "#f9a8d4", fontWeight: "normal" }] },
  { id: "streetwear", name: "Streetwear", emoji: "🧢", description: "Urban drop", backgroundColor: "#0a0a0a", transition: "slide", effect: "contrast", transitionDuration: 0.7, secondsPerSlide: 2.0, playbackSpeed: 1.15, texts: [{ text: "NEW DROP", x: 50, y: 26, fontSize: 36, color: "#fafafa", fontWeight: "bold" }, { text: "limited pieces", x: 50, y: 48, fontSize: 22, color: "#f97316", fontWeight: "bold" }, { text: "tap to cop", x: 50, y: 76, fontSize: 16, color: "#a3a3a3", fontWeight: "normal" }] },
  { id: "product", name: "Product", emoji: "📦", description: "UGC review", backgroundColor: "#1f2937", transition: "zoom", effect: "bright", transitionDuration: 0.9, secondsPerSlide: 2.6, playbackSpeed: 1.0, texts: [{ text: "Amazon find", x: 50, y: 24, fontSize: 18, color: "#fbbf24", fontWeight: "bold" }, { text: "under $20", x: 50, y: 48, fontSize: 34, color: "#ffffff", fontWeight: "bold" }, { text: "link in bio", x: 50, y: 76, fontSize: 18, color: "#d1d5db", fontWeight: "normal" }] },
  { id: "wedding", name: "Wedding", emoji: "💍", description: "Romantic film", backgroundColor: "#3f2e2e", transition: "crossfade", effect: "vintage", transitionDuration: 1.8, secondsPerSlide: 4.0, playbackSpeed: 0.7, texts: [{ text: "the day we said yes", x: 50, y: 26, fontSize: 18, color: "#f5d0c5", fontWeight: "normal" }, { text: "forever starts here", x: 50, y: 50, fontSize: 26, color: "#fff7ed", fontWeight: "bold" }, { text: "save the date", x: 50, y: 76, fontSize: 16, color: "#e7d5c5", fontWeight: "normal" }] },
  { id: "coffee", name: "Cafe", emoji: "☕", description: "Cozy cafe", backgroundColor: "#292524", transition: "crossfade", effect: "warm", transitionDuration: 1.5, secondsPerSlide: 3.2, playbackSpeed: 0.85, texts: [{ text: "best latte in town", x: 50, y: 26, fontSize: 20, color: "#d6d3d1", fontWeight: "normal" }, { text: "first sip hits", x: 50, y: 50, fontSize: 30, color: "#fef3c7", fontWeight: "bold" }, { text: "tag a coffee friend", x: 50, y: 76, fontSize: 16, color: "#a8a29e", fontWeight: "normal" }] },
  { id: "nightout", name: "Night Out", emoji: "🌃", description: "City neon", backgroundColor: "#020617", transition: "slide", effect: "cool", transitionDuration: 1.0, secondsPerSlide: 2.6, playbackSpeed: 1.05, texts: [{ text: "Friday energy", x: 50, y: 26, fontSize: 20, color: "#67e8f9", fontWeight: "normal" }, { text: "lights. city. us.", x: 50, y: 50, fontSize: 28, color: "#ffffff", fontWeight: "bold" }, { text: "who is coming?", x: 50, y: 76, fontSize: 16, color: "#94a3b8", fontWeight: "normal" }] }
];
